module.exports = {
  GET_DAY_STATE_COUNTS: 'GET_DAY_STATE_COUNTS',
  GET_DAY_POSTS: 'GET_DAY_POSTS',
  NEXT_MONTH: 'NEXT_MONTH',
  PREV_MONTH: 'PREV_MONTH',
  MONTH_VIEW: 'MONTH_VIEW',
  WEEK_VIEW: 'WEEK_VIEW',
  DAY_VIEW: 'DAY_VIEW'
}
